import fs from 'node:fs';
const root=new URL('../',import.meta.url);
const files=['index.html','styles.css','microduck-controls.css','src/editor.js','src/profiles.js','src/python-runtime.js','src/canonical-rig.js','src/source-simulator.js','src/simulator-host.js','src/task-catalog.js','src/task-workspace.js','src/microduck/baked-visual.js','src/microduck/command-catalog.js','src/microduck/command-bus.js','src/microduck/policy-simulator.js','src/microduck/python-bridge.js','src/microduck/rig-adapter.js','src/webmcp/agent-facade.js','src/webmcp/microduck-control.js','src/webmcp/register-ide-tools.js','src/app-v2.js','README.md','LICENSE','LICENSES/MIT.txt','THIRD_PARTY_NOTICES.md','docs/unitree-g1-rig.md','docs/microduck-simulator.md','licenses/unitree_ros-BSD-3-Clause.txt','licenses/microduck-apache-2.0.txt','licenses/microduck-third-party-notices.md','assets/microduck/manifest.json','assets/microduck/visual/duck.bin','.nojekyll','src/physics/lekiwi-source-audit.js','src/physics/lekiwi-kinematics.js','src/physics/lekiwi-model-package.js','src/physics/lekiwi-scene.js','src/physics/lekiwi-mujoco-worker.js','src/physics/lekiwi-task-evaluator.js','src/physics/lekiwi-physical-simulator.js','src/webmcp/lekiwi-physical-control.js','docs/physics/lekiwi-provenance.md','scripts/generate_lekiwi_models.py','scripts/lekiwi_courier_scene.py','native/lekiwi_reference.py','models/lekiwi/wheel_reference.xml','models/lekiwi/base.xml','models/lekiwi/base_stand.xml','models/lekiwi/base_lowtraction.xml','models/lekiwi/courier.xml','src/physics/unitree-g1-source-audit.js','src/physics/unitree-g1-controller.js','src/physics/unitree-g1-model-package.js','src/physics/unitree-g1-capabilities.js','src/physics/unitree-g1-scene.js','src/physics/unitree-g1-mujoco-worker.js','src/physics/unitree-g1-physical-simulator.js','src/webmcp/unitree-g1-physical-control.js','docs/physics/unitree-g1-provenance.md','docs/physics/unitree-g1-rig.md','scripts/prepare_unitree_g1_assets.py','scripts/generate_unitree_g1_models.py','native/unitree_g1_reference.py','models/unitree_g1/mounted.xml','models/unitree_g1/mounted_blocked.xml','models/unitree_g1/freebase.xml','models/unitree_g1/freebase_drop.xml','models/unitree_g1/source/MESH_MANIFEST.json'];
for(const f of files){if(!fs.existsSync(new URL(f,root)))throw new Error(`missing ${f}`)}
const index=fs.readFileSync(new URL('index.html',root),'utf8');
for(const token of ['id="editor"','id="simCanvas"','id="taskSelect"','value="unitree"','value="microduck"','id="microduckControlDeck"','id="modeChip"','id="simBadge"','src/app-v2.js','pyodide.js'])if(!index.includes(token))throw new Error(`index missing ${token}`);
for(const token of ['id="agentAccessControl"','data-agent-access="assist"'])if(!index.includes(token))throw new Error(`index missing WebMCP access control: ${token}`);
if(/blockly/i.test(index))throw new Error('Blockly dependency found');
for(const token of ['data-action="about"','id="aboutDialog"','Dr. Emil Jivishov','© 2026','MIT License','Open source under the MIT License.'])if(!index.includes(token))throw new Error('index missing About dialog content');
const all=files.filter(f=>f.endsWith('.js')||f.endsWith('.html')).map(f=>fs.readFileSync(new URL(f,root),'utf8')).join('\n');
for(const fake of ['robot.grasp(','robot.attach(','robot.teleport(','robot.move_to('])if(all.includes(fake))throw new Error(`fake physical method found: ${fake}`);
const css=fs.readFileSync(new URL('styles.css',root),'utf8');let depth=0;for(const c of css){if(c==='{')depth++;if(c==='}')depth--;if(depth<0)throw new Error('CSS braces unbalanced');}if(depth!==0)throw new Error('CSS braces unbalanced');
const profiles=fs.readFileSync(new URL('src/profiles.js',root),'utf8');
for(const token of ['SO101Follower','BiOpenArmFollower','LeKiwiClient','Unitree G1 29-DoF','unitree_g1_29dof','hardware_validation','RoboBuddy_AI@66d18a029a0caeb6a6075e681dbd9ecd6b22affa'])if(!profiles.includes(token))throw new Error(`profiles missing ${token}`);
if(/lightweight articulated browser model|intentionally simplified and is not a production OpenArm mesh/i.test(profiles))throw new Error('obsolete schematic-robot fidelity language remains');
const simulator=fs.readFileSync(new URL('src/source-simulator.js',root),'utf8');
for(const forbidden of ['_armVisual(','_buildSO101(','_buildLeKiwi(','segmentMesh('])if(simulator.includes(forbidden))throw new Error(`procedural placeholder rig remains: ${forbidden}`);
for(const required of ['CanonicalRobotRig','ScenarioV2Engine','engine.plant.sendAction','engine.plant.tick()','rigTransitionSeconds','contactModel'])if(!simulator.includes(required))throw new Error(`source simulator missing ${required}`);
const unitreeDoc=fs.readFileSync(new URL('docs/unitree-g1-rig.md',root),'utf8');
for(const token of ['29 named revolute joints','36 visual parts','dd4fa6866e523ad61324f658d63736e4eda3a6e4','not implement balance'])if(!unitreeDoc.includes(token))throw new Error(`Unitree rig documentation missing ${token}`);
const unitreeLicense=fs.readFileSync(new URL('licenses/unitree_ros-BSD-3-Clause.txt',root),'utf8');
for(const token of ['BSD 3-Clause License','HangZhou YuShu TECHNOLOGY','THIS SOFTWARE IS PROVIDED'])if(!unitreeLicense.includes(token))throw new Error(`Unitree license notice missing ${token}`);
const license=fs.readFileSync(new URL('LICENSE',root),'utf8');
for(const token of ['multi-license repository','Original RoboBuddy IDE source code is licensed under the MIT License','LICENSES/MIT.txt','MicroDuck 3D model and collision files','Creative Commons BY-SA-NC'])if(!license.includes(token))throw new Error(`repository license scope missing ${token}`);
const mitLicense=fs.readFileSync(new URL('LICENSES/MIT.txt',root),'utf8');
for(const token of ['MIT License','Copyright (c) 2026 Dr. Emil Jivishov','Permission is hereby granted, free of charge','THE SOFTWARE IS PROVIDED "AS IS"'])if(!mitLicense.includes(token))throw new Error('scoped MIT license missing required terms');
const notices=fs.readFileSync(new URL('THIRD_PARTY_NOTICES.md',root),'utf8');
for(const token of ['519142b1f5bf59fdfd44d06c205119e7fff8e3cb','3D model files are licensed under Creative Commons BY-SA-NC','does not name a Creative Commons version','models/microduck/source/','models/microduck/assets/'])if(!notices.includes(token))throw new Error(`third-party notice missing ${token}`);
if(/Creative Commons Attribution[^\n]*4\.0|CC BY-SA-NC 4\.0/i.test(`${license}\n${notices}`))throw new Error('repository must not invent a version for the upstream MicroDuck Creative Commons BY-SA-NC declaration');
const webmcp=fs.readFileSync(new URL('src/webmcp/register-ide-tools.js',root),'utf8');
for(const token of ['document.modelContext.registerTool','describe_robobuddy_task','read_robobuddy_workspace','inspect_robobuddy_simulation','focus_robobuddy_workspace','run_robobuddy_program','control_microduck_simulation'])if(!webmcp.includes(token))throw new Error(`WebMCP registration missing ${token}`);
const webmcpControl=fs.readFileSync(new URL('src/webmcp/microduck-control.js',root),'utf8');
for(const token of ['MICRODUCK_COMMANDS','oneOf','additionalProperties: false','duration_ms','boundedMicroDuckResult'])if(!webmcpControl.includes(token))throw new Error(`MicroDuck WebMCP control contract missing ${token}`);
const lekiwiAudit=fs.readFileSync(new URL('src/physics/lekiwi-source-audit.js',root),'utf8');
for(const token of ['efa608d7ee5a495a4803b1d28cd0c955b4f1e033','7e241bd630a3719a56157a497ce5d08f244784f1','75fe2669c0ab0b029986de424c69162071174df8','not-adopted','calibration-required'])if(!lekiwiAudit.includes(token))throw new Error(`LeKiwi source audit missing ${token}`);
const lekiwiWorker=fs.readFileSync(new URL('src/physics/lekiwi-mujoco-worker.js',root),'utf8');
if((lekiwiWorker.match(/data\.qpos\[[^\]]*\]\s*=/g)||[]).length!==1)throw new Error('LeKiwi worker must assign qpos only in declared initial state');
if(/data\.qvel\[[^\]]*\]\s*=/.test(lekiwiWorker))throw new Error('LeKiwi worker must never assign qvel');
const lekiwiPresentation=fs.readFileSync(new URL('src/physics/lekiwi-physical-simulator.js',root),'utf8');
for(const forbidden of ['integrateBase','this.baseX+=','this.baseYaw+=','applyAction(action)=>'])if(lekiwiPresentation.includes(forbidden))throw new Error(`LeKiwi presentation layer integrates motion: ${forbidden}`);
const lekiwiDoc=fs.readFileSync(new URL('docs/physics/lekiwi-provenance.md',root),'utf8');
for(const token of ['numerically-verified','hardware comparison','calibration-required','wheel_radius'])if(!lekiwiDoc.includes(token))throw new Error(`LeKiwi provenance doc missing ${token}`);
if(/hardware-compared`?\s*$/m.test(lekiwiDoc.split('\n').filter(l=>/^evidence:/.test(l)).join('\n')))throw new Error('LeKiwi must not claim hardware-compared evidence');
const lekiwiXml=['models/lekiwi/wheel_reference.xml','models/lekiwi/base.xml','models/lekiwi/base_stand.xml','models/lekiwi/base_lowtraction.xml','models/lekiwi/courier.xml'].map(f=>fs.readFileSync(new URL(f,root),'utf8'));
for(const xml of lekiwiXml){if(/<equality/.test(xml))throw new Error('LeKiwi models must not contain equality constraints');if(/<weld/.test(xml))throw new Error('LeKiwi models must not contain welds');}
const unitreeAudit=fs.readFileSync(new URL('src/physics/unitree-g1-source-audit.js',root),'utf8');
for(const token of ['dd4fa6866e523ad61324f658d63736e4eda3a6e4','1eb6642e3f3fdfb7fb13a9794fd6a2dd93ea0e7d','1425b15f73bd4095f0df53709d7c389c3eb9e790','not-adopted','PARAMETER_EVIDENCE.CALIBRATION_REQUIRED'])if(!unitreeAudit.includes(token))throw new Error(`Unitree G1 source audit missing ${token}`);
const unitreeWorker=fs.readFileSync(new URL('src/physics/unitree-g1-mujoco-worker.js',root),'utf8');
if(/data\.qpos\[[^\]]*\]\s*=/.test(unitreeWorker))throw new Error('Unitree G1 worker must never assign qpos');
if(/data\.qvel\[[^\]]*\]\s*=/.test(unitreeWorker))throw new Error('Unitree G1 worker must never assign qvel');
if((unitreeWorker.match(/data\.(\w+)\[[^\]]*\]\s*=/g)||[]).some(a=>!a.startsWith('data.ctrl[')))throw new Error('Unitree G1 worker must write only actuator torque into the plant');
const unitreePresentation=fs.readFileSync(new URL('src/physics/unitree-g1-physical-simulator.js',root),'utf8');
for(const forbidden of ['applyPhysicalRootPose(','this.pelvisZ+=','integrateRoot','snapToFloor'])if(unitreePresentation.includes(forbidden))throw new Error(`Unitree G1 presentation layer drives the plant: ${forbidden}`);
const unitreeProvenance=fs.readFileSync(new URL('docs/physics/unitree-g1-provenance.md',root),'utf8');
for(const token of ['numerically-verified','No hardware comparison exists','calibration-required','29 degrees of freedom, fixed rubber hands','unsupported'])if(!unitreeProvenance.includes(token))throw new Error(`Unitree G1 provenance doc missing ${token}`);
if(/hardware-compared/.test(unitreeProvenance))throw new Error('Unitree G1 must not claim hardware-compared evidence');
const unitreeXml=['models/unitree_g1/mounted.xml','models/unitree_g1/mounted_blocked.xml','models/unitree_g1/freebase.xml','models/unitree_g1/freebase_drop.xml'].map(f=>fs.readFileSync(new URL(f,root),'utf8'));
for(const xml of unitreeXml){if(/<equality/.test(xml))throw new Error('Unitree G1 models must not contain equality constraints');if(/<weld/.test(xml))throw new Error('Unitree G1 models must not contain welds');if(/<tendon/.test(xml))throw new Error('Unitree G1 models must not contain tendons');}
console.log('static fidelity checks: OK');