import fs from 'node:fs';
const root=new URL('../',import.meta.url);
const files=['index.html','styles.css','microduck-controls.css','src/editor.js','src/profiles.js','src/python-runtime.js','src/canonical-rig.js','src/source-simulator.js','src/simulator-host.js','src/task-catalog.js','src/task-workspace.js','src/microduck/baked-visual.js','src/microduck/command-catalog.js','src/microduck/command-bus.js','src/microduck/policy-simulator.js','src/microduck/python-bridge.js','src/microduck/rig-adapter.js','src/webmcp/agent-facade.js','src/webmcp/microduck-control.js','src/webmcp/register-ide-tools.js','src/app-v2.js','README.md','LICENSE','docs/unitree-g1-rig.md','docs/microduck-simulator.md','licenses/unitree_ros-BSD-3-Clause.txt','licenses/microduck-apache-2.0.txt','licenses/microduck-third-party-notices.md','assets/microduck/manifest.json','assets/microduck/visual/duck.bin','.nojekyll'];
for(const f of files){if(!fs.existsSync(new URL(f,root)))throw new Error(`missing ${f}`)}
const index=fs.readFileSync(new URL('index.html',root),'utf8');
for(const token of ['id="editor"','id="simCanvas"','id="taskSelect"','value="unitree"','value="microduck"','id="microduckControlDeck"','id="modeChip"','id="simBadge"','src/app-v2.js','pyodide.js'])if(!index.includes(token))throw new Error(`index missing ${token}`);
for(const token of ['id="agentAccessControl"','data-agent-access="assist"'])if(!index.includes(token))throw new Error(`index missing WebMCP access control: ${token}`);
if(/blockly/i.test(index))throw new Error('Blockly dependency found');
for(const token of ['data-action="about"','id="aboutDialog"','Dr. Emil Jivishov','© 2026','MIT License','Open source under the MIT License.'])if(!index.includes(token))throw new Error('index missing About dialog content');
const all=files.filter(f=>f.endsWith('.js')||f.endsWith('.html')).map(f=>fs.readFileSync(new URL(f,root),'utf8')).join('\n');
for(const fake of ['robot.grasp(','robot.attach(','robot.teleport(','robot.move_to('])if(all.includes(fake))throw new Error(`fake physical method found: ${fake}`);
const css=fs.readFileSync(new URL('styles.css',root),'utf8');let depth=0;for(const c of css){if(c==='{')depth++;if(c==='}')depth--;if(depth<0)throw new Error('CSS braces unbalanced');}if(depth!==0)throw new Error('CSS braces unbalanced');
const profiles=fs.readFileSync(new URL('src/profiles.js',root),'utf8');
for(const token of ['SO101Follower','BiOpenArmFollower','LeKiwiClient','Unitree G1 29-DoF','unitree_g1_29dof','hardware_validation','RoboBuddy_AI@66d18a029a0caeb6a6075e681dbd9ecd6b22affa'])if(!profiles.includes(token))throw new Error(`profiles missing ${token}`);
if(/lightweight articulated browser model|intentionally simplified and is not a production OpenArm mesh/i.test(profiles))throw new Error('obsolete schematic-robot fidelity language remains');
const simulator=fs.readFileSync(new URL('src/source-simulator.js',root),'utf8');
for(const forbidden of ['_armVisual(','_buildSO101(','_buildLeKiwi(','segmentMesh('])if(simulator.includes(forbidden))throw new Error(`procedural placeholder rig remains: ${forbidden}`);
for(const required of ['CanonicalRobotRig','ScenarioV2Engine','engine.plant.sendAction','engine.plant.tick()','rigTransitionSeconds','contactModel'])if(!simulator.includes(required))throw new Error(`source simulator missing ${required}`);
const unitreeDoc=fs.readFileSync(new URL('docs/unitree-g1-rig.md',root),'utf8');
for(const token of ['29 named revolute joints','36 visual parts','dd4fa6866e523ad61324f658d63736e4eda3a6e4','not implement balance'])if(!unitreeDoc.includes(token))throw new Error(`Unitree rig documentation missing ${token}`);
const unitreeLicense=fs.readFileSync(new URL('licenses/unitree_ros-BSD-3-Clause.txt',root),'utf8');
for(const token of ['BSD 3-Clause License','HangZhou YuShu TECHNOLOGY','THIS SOFTWARE IS PROVIDED'])if(!unitreeLicense.includes(token))throw new Error(`Unitree license notice missing ${token}`);
const license=fs.readFileSync(new URL('LICENSE',root),'utf8');
for(const token of ['MIT License','Copyright (c) 2026 Dr. Emil Jivishov','Permission is hereby granted, free of charge','THE SOFTWARE IS PROVIDED "AS IS"'])if(!license.includes(token))throw new Error('license missing required MIT terms');
if(license.includes('PolyForm Noncommercial'))throw new Error('obsolete non-commercial license remains');
const webmcp=fs.readFileSync(new URL('src/webmcp/register-ide-tools.js',root),'utf8');
for(const token of ['document.modelContext.registerTool','describe_robobuddy_task','read_robobuddy_workspace','inspect_robobuddy_simulation','focus_robobuddy_workspace','run_robobuddy_program','control_microduck_simulation'])if(!webmcp.includes(token))throw new Error(`WebMCP registration missing ${token}`);
const webmcpControl=fs.readFileSync(new URL('src/webmcp/microduck-control.js',root),'utf8');
for(const token of ['MICRODUCK_COMMANDS','oneOf','additionalProperties: false','duration_ms','boundedMicroDuckResult'])if(!webmcpControl.includes(token))throw new Error(`MicroDuck WebMCP control contract missing ${token}`);
console.log('static fidelity checks: OK');
