#!/usr/bin/env python3
"""Add experimental numerical variants; never rewrite the Menlo reference models."""
import hashlib,json
from pathlib import Path
import xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]

def generate():
    audit=json.loads((ROOT/'models/asimov/source/audit.json').read_text())
    output=ROOT/'models/asimov/actuator';output.mkdir(exist_ok=True)
    result={}
    for variant in ['mounted','freebase']:
        raw=(ROOT/f'models/asimov/{variant}.xml').read_bytes()
        assert hashlib.sha256(raw).hexdigest()==audit['modelHashes'][variant]
        x=ET.fromstring(raw)
        x.set('model',f'robobuddy-asimov-actuator-{variant}-v1')
        # 200 Hz controller timing remains unchanged; tighter integration is not
        # represented as more accurate hardware parameters.
        x.find('option').set('timestep','0.0025')
        # Source has zero damping/frictionloss. Assert rather than quietly
        # layering our explicit friction law on an unknown future source model.
        for j in x.findall('.//worldbody//joint'):
            assert float(j.get('damping','0'))==0 and float(j.get('frictionloss','0'))==0
        ET.indent(x,space='  ')
        data=ET.tostring(x,encoding='utf-8',xml_declaration=True)+b'\n'
        (output/f'{variant}.xml').write_bytes(data)
        result[variant]={'asset':f'models/asimov/actuator/{variant}.xml','sha256':hashlib.sha256(data).hexdigest(),'timestepSeconds':.0025}
    (ROOT/'src/physics/asimov-actuator-generated.js').write_text('// Generated by scripts/generate_asimov_actuator_models.py.\nexport const ASIMOV_ACTUATOR_MODELS = Object.freeze('+json.dumps(result,separators=(',',':'))+');\n')
    print(json.dumps(result))
if __name__=='__main__':generate()
